# Generated by Django 5.1.4 on 2024-12-10 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WING', 'Wing'), ('BODY', 'Body'), ('TAIL', 'Tail'), ('AVIONICS', 'Avionics')], max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WING', 'Wing Team'), ('BODY', 'Body Team'), ('TAIL', 'Tail Team'), ('AVIONICS', 'Avionics Team'), ('ASSEMBLY', 'Assembly Team')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='year_of_manufacture',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='assembly_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='name',
            field=models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'Akinci'), ('KIZILELMA', 'Kizilelma')], max_length=50),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='aircraft_production.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPartAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_teams', to='aircraft_production.part')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='aircraft_production.team')),
            ],
        ),
        migrations.CreateModel(
            name='AircraftPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='aircraft_production.aircraft')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts', to='aircraft_production.part')),
            ],
            options={
                'unique_together': {('aircraft', 'part')},
            },
        ),
    ]
