# Generated by Django 5.1.4 on 2024-12-10 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_production', '0004_aircraftpart_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducedAircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('produced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
